/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Service.NhanVien_Service;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.NhanVien;
import utils.Auth;
import utils.JavaMails;

/**
 *
 * @author HP
 */
public class Frame_QuenMatKhau extends javax.swing.JFrame {

    NhanVien_Service service_NhanVien = new NhanVien_Service();

    /**
     * Creates new form Frame_QuenMatKhau
     */
    public Frame_QuenMatKhau() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quên mật khẩu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nhapEmail = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_OTP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_thayDoi = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        txt_nhapMatKhauMoi = new javax.swing.JPasswordField();
        txt_xacNhanMatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro SemiBold", 1, 18)); // NOI18N
        jLabel1.setText("Quên mật khẩu");

        jLabel2.setText("Nhập Email");

        btn_send.setBackground(new java.awt.Color(255, 102, 0));
        btn_send.setText("Send OTP");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã OTP");

        jLabel4.setText("Nhập mật khẩu mới ");

        jLabel5.setText("Nhập mật khẩu mới ");

        btn_thayDoi.setBackground(new java.awt.Color(255, 102, 0));
        btn_thayDoi.setText("Thay đổi");
        btn_thayDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thayDoiActionPerformed(evt);
            }
        });

        btn_huy.setBackground(new java.awt.Color(255, 102, 0));
        btn_huy.setText("Hủy bỏ");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        txt_nhapMatKhauMoi.setText("jPasswordField1");

        txt_xacNhanMatKhau.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_nhapEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_send))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btn_thayDoi)
                                .addGap(18, 18, 18)
                                .addComponent(btn_huy))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_nhapMatKhauMoi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_OTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(txt_xacNhanMatKhau, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nhapEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nhapMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_xacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_thayDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        Auth.clearOtp();
        cancel();
    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_thayDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thayDoiActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            if (Auth.getotp() != null && Auth.getotp().equalsIgnoreCase(txt_OTP.getText())) {
                doimatkhau();
                Auth.clearOtp();
            } else {
                JOptionPane.showMessageDialog(this, "Mã Xác Nhận Không Chính Xác", "Thông Báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_thayDoiActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        if (checkValidateMail()) {
            if (service_NhanVien.findByEmail(txt_nhapEmail.getText().trim()) != null) {
                Auth.RandomOtp();
                JavaMails.sendmail(txt_nhapEmail.getText(), "Ma OTP La: " + Auth.getotp(), "Lay Lai Mat Khau");
                JOptionPane.showMessageDialog(this, "Gui Ma Thanh Cong");
            } else if (service_NhanVien.findByEmail(txt_nhapEmail.getText()) == null) {
                JOptionPane.showMessageDialog(this, "Email nhân viên không tồn tại trên hệ thống", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_QuenMatKhau().setVisible(true);
            }
        });
    }

    public void doimatkhau() {
        String email = txt_nhapEmail.getText();
        String matkhau1 = new String(txt_nhapMatKhauMoi.getPassword());
        String matkhau2 = new String(txt_xacNhanMatKhau.getPassword());
        if (!matkhau1.equals(matkhau2)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không chính xác", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                NhanVien nv = service_NhanVien.findByEmail(email);
                nv.setPasswork(matkhau1);
                service_NhanVien.updateNhanVienQMK(nv);
                JOptionPane.showMessageDialog(this, "Đã cập nhật mật khẩu thành công", "Thông báo", JOptionPane.WARNING_MESSAGE);
                cancel();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }

    public void cancel() {
        this.dispose();
        new DangNhap().setVisible(true);
    }

    public boolean checkValidateMail() {
        try {

            String chkemail = "\\w+@\\w{3,8}+\\.+\\w{2,4}";
            if (txt_nhapEmail.getText().trim().equals("")) {
                txt_nhapEmail.requestFocus();
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Email", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if (!txt_nhapEmail.getText().matches(chkemail)) {
                txt_nhapEmail.requestFocus();
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng email", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (HeadlessException headlessException) {
            System.out.println("Lỗi validate QuenMk");
        }
        return true;
    }

    public boolean validateForm() {
        String otp = txt_OTP.getText().trim();
        String mk1 = new String(txt_nhapMatKhauMoi.getPassword());
        String mk2 = new String(txt_xacNhanMatKhau.getPassword());
        if (otp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập OTP", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (mk1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (mk2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập xác nhận mật khẩu", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton btn_thayDoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_OTP;
    private javax.swing.JTextField txt_nhapEmail;
    private javax.swing.JPasswordField txt_nhapMatKhauMoi;
    private javax.swing.JPasswordField txt_xacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
